CREATE TABLE trainer_reviews (
    id BIGSERIAL PRIMARY KEY,
    training_session_id BIGINT NOT NULL UNIQUE
        REFERENCES training_sessions(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    rating SMALLINT NOT NULL CHECK (rating BETWEEN 1 AND 5),
    feedback TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
