package routes

import (
	"github.com/dienulhaq/go-driving-course-management/config"
	"github.com/dienulhaq/go-driving-course-management/handlers"
	"github.com/dienulhaq/go-driving-course-management/middleware"
	"github.com/dienulhaq/go-driving-course-management/models"
	"github.com/dienulhaq/go-driving-course-management/repositories"
	"github.com/dienulhaq/go-driving-course-management/services"
	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
	"gorm.io/gorm"
)

func New(db *gorm.DB, cfg config.Config) (*gin.Engine, error) {
	tokens, err := services.NewJWTManager(cfg.JWTSecret, cfg.JWTExpiresIn)
	if err != nil {
		return nil, err
	}
	users := repositories.NewUserRepository(db)
	authHandler := handlers.NewAuthHandler(services.NewAuthService(users, tokens))
	adminUsers := repositories.NewAdminUserRepository(db)
	masterData := repositories.NewMasterDataRepository(db)
	adminHandler := handlers.NewAdminHandler(services.NewAdminService(adminUsers, masterData))
	enrollments := repositories.NewEnrollmentRepository(db)
	enrollmentHandler := handlers.NewEnrollmentHandler(services.NewEnrollmentService(enrollments))
	availabilities := repositories.NewAvailabilityRepository(db)
	availabilityHandler := handlers.NewAvailabilityHandler(services.NewAvailabilityService(availabilities))
	trainingSessions := repositories.NewTrainingSessionRepository(db)
	trainingSessionHandler := handlers.NewTrainingSessionHandler(services.NewTrainingSessionService(trainingSessions))
	internalHandler := handlers.NewInternalHandler(db)

	router := gin.New()
	router.Use(gin.Logger(), gin.Recovery())
	router.GET("/health", handlers.NewHealthHandler(db).Health)
	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
	internal := router.Group("/api/v1/internal")
	internal.Use(middleware.BasicAuth(cfg.BasicAuthUser, cfg.BasicAuthPass))
	internal.GET("/health", internalHandler.Health)
	internal.GET("/stats", internalHandler.Stats)

	usersAPI := router.Group("/api/users")
	usersAPI.POST("/register", authHandler.Register)
	usersAPI.POST("/login", authHandler.Login)

	authAPI := router.Group("/api/v1/auth")
	authAPI.Use(middleware.JWTAuth(tokens, users))
	authAPI.GET("/me", authHandler.Me)

	student := router.Group("/api/v1/student")
	student.Use(middleware.JWTAuth(tokens, users), middleware.RoleAuth(models.RoleStudent))
	student.GET("/packages", enrollmentHandler.StudentListPackages)
	student.GET("/packages/:id", enrollmentHandler.StudentGetPackage)
	student.POST("/enrollments", enrollmentHandler.StudentCreateEnrollment)
	student.GET("/enrollments", enrollmentHandler.StudentListEnrollments)
	student.GET("/enrollments/:id", enrollmentHandler.StudentGetEnrollment)
	student.GET("/enrollments/:id/payment", enrollmentHandler.StudentGetEnrollmentPayment)
	student.POST("/payments/:id/pay", enrollmentHandler.StudentPayPayment)
	student.GET("/invoices", enrollmentHandler.StudentListInvoices)
	student.GET("/invoices/:id", enrollmentHandler.StudentGetInvoice)
	student.GET("/schedules", availabilityHandler.StudentListSchedules)
	student.POST("/training-sessions", trainingSessionHandler.StudentBookSession)
	student.GET("/training-sessions", trainingSessionHandler.StudentListSessions)
	student.GET("/training-sessions/:id", trainingSessionHandler.StudentGetSession)
	student.PATCH("/training-sessions/:id/cancel", trainingSessionHandler.StudentCancelSession)
	student.POST("/training-sessions/:id/reschedule", trainingSessionHandler.StudentRescheduleSession)
	student.GET("/skills", trainingSessionHandler.StudentCurrentSkills)
	student.GET("/skills/history", trainingSessionHandler.StudentSkillHistory)
	student.POST("/training-sessions/:id/review", trainingSessionHandler.StudentCreateReview)
	student.PUT("/training-sessions/:id/review", trainingSessionHandler.StudentUpdateReview)
	student.GET("/training-sessions/:id/review", trainingSessionHandler.StudentGetReview)
	student.GET("/certificates", trainingSessionHandler.StudentListCertificates)
	student.GET("/certificates/:id", trainingSessionHandler.StudentGetCertificate)

	trainer := router.Group("/api/v1/trainer")
	trainer.Use(middleware.JWTAuth(tokens, users), middleware.RoleAuth(models.RoleTrainer))
	trainer.POST("/availabilities", availabilityHandler.TrainerCreateAvailability)
	trainer.GET("/availabilities", availabilityHandler.TrainerListAvailabilities)
	trainer.GET("/availabilities/:id", availabilityHandler.TrainerGetAvailability)
	trainer.PUT("/availabilities/:id", availabilityHandler.TrainerUpdateAvailability)
	trainer.PATCH("/availabilities/:id/cancel", availabilityHandler.TrainerCancelAvailability)
	trainer.GET("/training-sessions", trainingSessionHandler.TrainerListSessions)
	trainer.GET("/training-sessions/:id", trainingSessionHandler.TrainerGetSession)
	trainer.POST("/training-sessions/:id/start", trainingSessionHandler.TrainerStartSession)
	trainer.PUT("/training-sessions/:id/assessments", trainingSessionHandler.TrainerUpsertAssessments)
	trainer.GET("/training-sessions/:id/assessments", trainingSessionHandler.TrainerGetAssessments)
	trainer.PUT("/training-sessions/:id/evaluation", trainingSessionHandler.TrainerUpsertEvaluation)
	trainer.GET("/training-sessions/:id/evaluation", trainingSessionHandler.TrainerGetEvaluation)
	trainer.GET("/training-sessions/:id/student-progress", trainingSessionHandler.TrainerStudentProgress)
	trainer.POST("/training-sessions/:id/complete", trainingSessionHandler.TrainerCompleteSession)
	trainer.GET("/reviews", trainingSessionHandler.TrainerListReviews)
	trainer.GET("/reviews/summary", trainingSessionHandler.TrainerGetReviewSummary)

	admin := router.Group("/api/v1/admin")
	admin.Use(middleware.JWTAuth(tokens, users), middleware.RoleAuth(models.RoleAdmin))
	admin.POST("/trainers", adminHandler.CreateTrainer)
	admin.GET("/trainers", adminHandler.ListTrainers)
	admin.GET("/trainers/:id", adminHandler.GetTrainer)
	admin.PUT("/trainers/:id", adminHandler.UpdateTrainer)
	admin.PATCH("/trainers/:id/status", adminHandler.UpdateTrainerStatus)
	admin.GET("/students", adminHandler.ListStudents)
	admin.GET("/students/:id", adminHandler.GetStudent)
	admin.PATCH("/students/:id/status", adminHandler.UpdateStudentStatus)
	admin.POST("/packages", adminHandler.CreatePackage)
	admin.GET("/packages", adminHandler.ListPackages)
	admin.GET("/packages/:id", adminHandler.GetPackage)
	admin.PUT("/packages/:id", adminHandler.UpdatePackage)
	admin.PATCH("/packages/:id/status", adminHandler.UpdatePackageStatus)
	admin.POST("/materials", adminHandler.CreateMaterial)
	admin.GET("/materials", adminHandler.ListMaterials)
	admin.GET("/materials/:id", adminHandler.GetMaterial)
	admin.PUT("/materials/:id", adminHandler.UpdateMaterial)
	admin.PATCH("/materials/:id/status", adminHandler.UpdateMaterialStatus)
	admin.POST("/materials/:id/sub-materials", adminHandler.CreateSubMaterial)
	admin.GET("/materials/:id/sub-materials", adminHandler.ListSubMaterials)
	admin.GET("/sub-materials/:id", adminHandler.GetSubMaterial)
	admin.PUT("/sub-materials/:id", adminHandler.UpdateSubMaterial)
	admin.PATCH("/sub-materials/:id/status", adminHandler.UpdateSubMaterialStatus)
	admin.GET("/enrollments", enrollmentHandler.AdminListEnrollments)
	admin.GET("/enrollments/:id", enrollmentHandler.AdminGetEnrollment)
	admin.GET("/payments", enrollmentHandler.AdminListPayments)
	admin.GET("/payments/:id", enrollmentHandler.AdminGetPayment)
	admin.GET("/invoices", enrollmentHandler.AdminListInvoices)
	admin.GET("/invoices/:id", enrollmentHandler.AdminGetInvoice)
	admin.GET("/trainer-availabilities", availabilityHandler.AdminListAvailabilities)
	admin.GET("/trainer-availabilities/:id", availabilityHandler.AdminGetAvailability)
	admin.POST("/trainer-availabilities/:id/publish", availabilityHandler.AdminPublishAvailability)
	admin.PATCH("/trainer-availabilities/:id/cancel", availabilityHandler.AdminCancelAvailability)
	admin.GET("/training-sessions", trainingSessionHandler.AdminListSessions)
	admin.GET("/training-sessions/:id", trainingSessionHandler.AdminGetSession)
	admin.PATCH("/training-sessions/:id/cancel", trainingSessionHandler.AdminCancelSession)
	admin.POST("/training-sessions/:id/reschedule", trainingSessionHandler.AdminRescheduleSession)
	admin.GET("/trainer-reviews", trainingSessionHandler.AdminListReviews)
	admin.GET("/trainers/:id/reviews", trainingSessionHandler.AdminListTrainerReviews)
	admin.GET("/certificates", trainingSessionHandler.AdminListCertificates)
	admin.GET("/certificates/:id", trainingSessionHandler.AdminGetCertificate)
	return router, nil
}
